[file_name, file_path, ~] = uigetfile('*.set');


options = {'format', 'matrix', 'datatype', 'channels', ...
           'erp', 'on', ...
           'spec', 'off', ...
           'ersp', 'off', ...
           'itc', 'off', ...
           'rmicacomps','on', ...
           'erpparams', [], 'specparams', [], 'erspparams', [], ...
           'interp', 'off', ...
           'scalp', 'off', ...
           'recompute', 'on', ...
           'savetrials', 'on'};
       
       
limo_create_single_trials(fullfile(file_path, file_name), options{:})