function epBlock = defineBlocksSeperatePT123(EEG)
% define trial blocks into IL, TR, PT1, PT2, and PT3
nep = length(EEG.epoch);
context = cell(nep, 1);
for i = 1:nep, context(i, 1) = EEG.epoch(i).eventcond(1); end

block = { find(strcmpi(context, 'IL')), ...
          find(strcmpi(context, 'TR')), ...
          find(strcmpi(context, 'PT1')), ...
          find(strcmpi(context, 'PT2')), ...
          find(strcmpi(context, 'PT3')) };

% block ep into IL1, IL2~19, TR1, TR2~19, PT1 1, PT1 2~19, PT2 1, PT2 2~19, PT 3, PT3 2~19
epBlock = { block{1}(1), block{1}(2:end), ...
            block{2}(1), block{2}(2:end), ...
            block{3}(1), block{3}(2:end), ...
            block{4}(1), block{4}(2:end), ...
            block{5}(1), block{5}(2:end) };
end